---

- name: Set the Github API endpoint
  set_fact:
    _node_exporter_github_api_url: |-
      {% if node_exporter_release_tag == 'latest' %}
      https://api.github.com/repos/prometheus/node_exporter/releases/latest
      {% else %}
      https://api.github.com/repos/prometheus/node_exporter/releases/tags/{{ node_exporter_release_tag }}
      {% endif %}

- name: Set the Github API token
  set_fact:
    _node_exporter_github_api_token: "{{ lookup('env', 'GITHUB_API_TOKEN') }}"

- name: Fetch the node-exporter release information from Github
  uri:
    url: "{{ _node_exporter_github_api_url }}"
    method: GET
    headers:
      Authorization: "{% if _node_exporter_github_api_token %}token {{ _node_exporter_github_api_token }}{% endif %}"
  check_mode: no
  register: _node_exporter_github_release
  until: |
    'status' in _node_exporter_github_release
      and _node_exporter_github_release['status'] == 200
  retries: 5
  delay: 15

- name: Get the tag of the latest node-exporter Github release
  set_fact:
    node_exporter_release_tag: "{{ _node_exporter_github_release['json'] | json_query('tag_name') }}"
  when: node_exporter_release_tag == "latest"

- name: Set the Github download URL for the node-exporter release
  set_fact:
    node_exporter_release_url: "{{ _node_exporter_github_release['json'] | json_query(_node_exporter_release_asset_url_query) }}"
  vars:
    _node_exporter_release_asset_url_query: "assets[?name=='{{ hostvars[inventory_hostname] | node_exporter_release_build(node_exporter_release_tag) }}.tar.gz'] | [0].browser_download_url"  # noqa 204
